# Use the official Python base image
FROM python:3.12.1

# Set the working directory in the container
WORKDIR /app

# Copy the Python script into the container
COPY app.py /app/app.py

# Install any dependencies
RUN pip install opencv-python-headless
RUN pip install pillow

# Set environment variables (if needed)
# ENV VARIABLE_NAME value

# Run the Python script when the container launches
CMD ["python", "app.py"]
